make:
	g++ -o sender_sigalrm sender_sigalrm.cpp
	g++ -o receiver_sigalrm receiver_sigalrm.cpp
	g++ -o sender_select sender_select.cpp
	g++ -o receiver_select receiver_select.cpp
	g++ -o sender_sockopt sender_sockopt.cpp
	g++ -o receiver_sockopt receiver_sockopt.cpp

clean:
	rm -f sender_sigalrm receiver_sigalrm sender_select receiver_select sender_sockopt receiver_sockopt